org: adambalassa
app: debter-server
service: debter-server
frameworkVersion: '3'

provider:
  name: aws
  runtime: java11
  profile: serverless
  region: eu-central-1
  environment:
    DYNAMODB_TABLE: debter
  timeout: 20
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:CreateTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

        - Effect: Allow
          Action:
            - dynamodb:ListTables
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/*"

package:
  artifact: build/libs/debter-0.0.1-SNAPSHOT.jar

layers:
  dependencies:
    path: build/layer

functions:
  # Room handler

  entrypoint:
    handler: hu.balassa.debter.handler.Handler
    events:
      - httpApi: { method: get,   path: '/room/{roomKey}' }
      - httpApi: { method: get,   path: '/room/{roomKey}/summary' }
      - httpApi: { method: post,  path: '/room' }
      - httpApi: { method: post,  path: '/room/{roomKey}/members' }
      - httpApi: { method: put,   path: '/room/{roomKey}/members' }
      - httpApi: { method: delete,path: '/room/{roomKey}/members/{memberId}' }
      - httpApi: { method: get,   path: '/room/{roomKey}/members' }
      - httpApi: { method: get,   path: '/room/{roomKey}/settings' }
      - httpApi: { method: put,   path: '/room/{roomKey}/settings' }
      - httpApi: { method: get,   path: '/room/{roomKey}/payments' }
      - httpApi: { method: post,  path: '/room/{roomKey}/payments' }
      - httpApi: { method: patch, path: '/room/{roomKey}/payments/{paymentId}' }
      - httpApi: { method: delete,path: '/room/{roomKey}/payments/{paymentId}' }
      - httpApi: { method: get,   path: '/room/{roomKey}/debts' }
    layers: [{ Ref: DependenciesLambdaLayer }]
