server:
  port: 8080
spring:
  application:
    name: Debter Server
info:
  version: '@version@'
fixer:
  host: http://data.fixer.io
  api-key: 5b84246bf4897159cfa64baa7eab657d
management.endpoints.web.cors:
  allowed-origins: https://debter.netlify.app/
  allowed-methods: GET

---
spring:
  profiles:
    active: develop
amazon:
  dynamodb:
    endpoint: http://localhost:8081/
    tableName: debter
  aws:
    accesskey: key
    secretkey: key2

---
spring:
  profiles:
    active: production